version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432'
    environment:
      - POSTGRES_USER=${user}
      - POSTGRES_PASSWORD=${password}
      - POSTGRES_DB=${database}
